### ISSUE TITLE
[MDB] Restore Context Area around diff from MDB1

### ISSUE THREAD

**Issue by ZeWaka** [spacestation13/BYONDDiffBots#13]
See:
![Screenshot_20220531-223322.png](https://user-images.githubusercontent.com/4741640/171334727-a0f597f7-7b20-4a6e-906f-22cdcaccb4ad.png)
![Screenshot_20220531-223335.png](https://user-images.githubusercontent.com/4741640/171334736-c3dec60f-5b7d-48d6-9f0b-bc4beb0efbf8.png)

**Comment by ToasterBiome** [comment]
Seconding this, we get a few PRs like this

![image](https://user-images.githubusercontent.com/5091394/183266986-7ca28c79-656d-4a1e-b414-88f5f3165440.png)

**Comment by AffectedArc07** [comment]
Believe this to be fixed now
