### ISSUE TITLE
[IDB] Icon state previews are consistently failing to generate

### ISSUE THREAD

**Issue by GoldenAlpharex** [spacestation13/BYONDDiffBots#23]
Basically, title says it all. It just links to resources that don't seem to actually exist.

[Here's the most recent example I can give you](https://github.com/Skyrat-SS13/Skyrat-tg/pull/22518/checks?check_run_id=15453674910).

**Comment by AffectedArc07** [comment]
Closed as not a code issue - I made a config fuckup
