### ISSUE TITLE
[IDB + MDB] Feature request: support for private repositories

### ISSUE THREAD

**Issue by DisturbHerb** [spacestation13/BYONDDiffBots#26]
Due to how repos are cloned by IDB and MDB, it's not possible for them to create diffs for private git respositories. I'd like to just hand an access token and have that squared away. @Cyberboss

**Comment by AffectedArc07** [comment]
Note - only MDB clones repos. IDB might work, but no guarantee.

**Comment by Cyberboss** [comment]
I'm waiting on a resolution to #21 before starting this

**Comment by AffectedArc07** [comment]
> I'm waiting on a resolution to #21 before starting this

Im waiting on a review from someone who knows what they are doing to merge it

**Comment by AffectedArc07** [comment]
I merged it
